version: 2.1

orbs:
  reporting: ministryofjustice/hmpps-reporting@1.0.6
  
workflows:
  checkout-build-publish:
    jobs:
      - reporting/gradle_owasp_check:
          notify_slack: true
          channel: dpr_cicd_alerts    
      - reporting/gradle_build_publish:
          app: digital-prison-reporting-java-template
          app_artifacts_directory: build/libs/
          bucket_prefix: dpr-artifact-store
          build_args: --debug
          notify_jira: true
          notify_slack: false
          filters:
            branches:
              only: /.*/
            tags:
              ignore: /.*/
          context:
            - hmpps-reporting-common
            - hmpps-reporting-orb ## Required for JIRA, needs reviewing

