version: 2.1

orbs:
  reporting: ministryofjustice/hmpps-reporting@1.0.8
  
workflows:
  checkout-build-publish:
    jobs:
      - reporting/gradle_owasp_check: ## OWASP Checks
          notify_slack: true
          context:
            - hmpps-reporting-common ## Reporting Common ORB
            - hmpps-reporting-orb ## Required for JIRA, needs reviewing
            - hmpps-common-vars ## Common ORB, Slack ALerts
          filters:
            branches:
              only: main ## Run for Main                
      - reporting/gradle_build_publish: ## Test, Build and Publish
          tag: "11.0" ## Defaults to 11.0
          app: digital-prison-reporting-java-template ## AppName, Repo Name
          app_artifacts_directory: build/libs/ ## Build Artifacts Location
          bucket_prefix: dpr-artifact-store ## S3 Artifacts Store, Defaults to "dpr-artifact-store"
          build_args: --debug ## Build Extra Args
          notify_jira: true ## Notify Jira
          notify_slack: true ## Notify Slack
          filters:
            branches:
              only: /.*/
            tags:
              ignore: /.*/
          ref: << pipeline.git.branch >><< pipeline.git.tag >>  
          context:
            - hmpps-reporting-common ## Reporting Common ORB 
            - hmpps-reporting-orb ## Required for JIRA, needs reviewing
            - hmpps-common-vars ## Common ORB, Slack ALerts

  owasp-security: ## Security Jobs Cron
    triggers:
      - schedule:
          cron: "30 7 * * *" ## Runs everyday at 7.30 AM
          filters:
            branches:
              only:
                - main
    jobs:
      - reporting/gradle_owasp_check:
          notify_slack: true
          channel: dpr_cicd_alerts ## May be Seperate Channel 
          context:
            - hmpps-reporting-common ## Reporting Common ORB
            - hmpps-reporting-orb ## Required for JIRA, needs reviewing
            - hmpps-common-vars ## Common ORB, Slack ALerts
          cache_key: "v4"
