version: 2.1

orbs:
  reporting: ministryofjustice/hmpps-reporting@dev:37ba9de36b2e607584eeb7e4bda36ca1ff42df89

parameters:
  GHA_Actor:
    type: string
    default: ""
  GHA_Action:
    type: string
    default: ""
  GHA_Event:
    type: string
    default: ""
  GHA_Meta:
    type: string
    default: ""

workflows:
  checkout-build-publish:
    when: 
      not: << pipeline.parameters.GHA_Action >>
    jobs:
    #  - reporting/gradle_owasp_check: ## OWASP Checks
    #      notify_slack: false
    #      context:
    #        - hmpps-reporting-common ## Reporting Common ORB
    #        - hmpps-reporting-orb ## Required for JIRA, needs reviewing
    #      filters:
    #        branches:
    #          only: main ## Run for Main, Before Code is promoted to Release/Prod                
      - reporting/gradle_build_publish: ## Test, Build and Publish
          tag: "11.0" ## Defaults to 11.0
          app: digital-prison-reporting-java-template ## AppName, Repo Name
          app_artifacts_directory: build/libs/ ## Build Artifacts Location
          bucket_prefix: dpr-artifact-store ## S3 Artifacts Store, Defaults to "dpr-artifact-store"
          build_args: --debug ## Build Extra Args
          sync_args: "--exclude '*' --include '*jar'" ## Extra Args for Artifacts Sync, OPTIONAL
          deploy_script: true ## Deploy Placeholder Script for GlueJobs, defaults to False         
          notify_jira: false ## Notify Jira
          notify_slack: false ## Notify Slack
          deploy_to_test: true
          branch: << pipeline.git.branch >><< pipeline.git.tag >>
          channel: dpr_cicd_alerts
          filters:
            branches:
              only: /.*/
            tags:
              ignore: /.*/
          ref: << pipeline.git.branch >><< pipeline.git.tag >>  
          context:
            - hmpps-reporting-common ## Reporting Common ORB 
            - hmpps-reporting-orb ## Required for JIRA, needs reviewing
  release:
    when: << pipeline.parameters.GHA_Action >>
    jobs:            
      - reporting/gradle_release:
          app: digital-prison-reporting-jobs
          sync_args: "--exclude '*' --include '*-all*jar'"
          release_ready: true
          notify_slack: false
          context:
            - hmpps-reporting-common
  