version: 2.1

orbs:
  reporting: ministryofjustice/hmpps-reporting@1.0.3
  
workflows:
  checkout-build-publish:
    jobs:
      - reporting/gradle_build_publish:
          app_src_directory: .
          app_artifacts_directory: build/libs/
          bucket_prefix: dpr-artifact-store
          bucket_path: digital-prison-reporting-java-template
          s3_sync_args: ""
          build_args: "--debug"
          notify_jira: true
          notify_slack: true
          filters:
            branches:
              only: /.*/
            tags:
              ignore: /.*/
          context:
            - digital-prison-reporting-dev
            - hmpps-common-vars
