version: 2.1

orbs:
  reporting: ministryofjustice/hmpps-reporting@dev:37ba9de36b2e607584eeb7e4bda36ca1ff42df89

workflows:
  release-pipeline:
    jobs:
      - reporting/gradle_release:
          app: digital-prison-reporting-jobs
          sync_args: "--exclude '*' --include '*-all*jar'"
          release_ready: true
          notify_slack: false
          context:
            - hmpps-reporting-common